name: HorizonGS

channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.8.19
  - pip=24.2

  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8

  - cuda-nvcc=11.8

  - pytorch-scatter

  - cmake
  - ninja
  - setuptools
  - wheel

  - pip:
      - plyfile
      - tensorboard
      - tqdm
      - einops
      - wandb
      - lpips
      - laspy
      - jaxtyping
      - colorama
      - opencv-python
      - scikit-learn
